FROM node:18-alpine

WORKDIR /app

# Installation des dépendances
COPY package*.json ./
RUN npm ci

# Copie du code source
COPY . .

# Construction du projet
RUN npm run build

# Exécution des tests
CMD ["npm", "run", "test:e2e"] 